include required("generated.conveyor.conf")

app {
	vcs-url = "https://github.com/gdude2002/ScanManager"

	windows {
		store {
			identity-name = "GarethColes.ScanManager"
			publisher = "CN=AA62E1DE-1AF9-4E50-A4A7-74AD20AF6FD3"
			publisher-display-name = "Gareth Coles"

			store-id = "9MZ9FWV42BD1"
		}

		certificate = "self signed by "${app.windows.store.publisher}
	}
}

conveyor.compatibility-level = 18
