#
# Copyrighted (Gareth Coles, 2024). Licensed under the EUPL-1.2
# with the specific provision (EUPL articles 14 & 15) that the
# applicable law is the (Republic of) Irish law and the Jurisdiction
# Dublin.
# Any redistribution must include the specific provision above.
#

org.slf4j.simpleLogger.dateTimeFormat=dd/MM/yyyy HH:mm:ss.SSS
org.slf4j.simpleLogger.levelInBrackets=true
org.slf4j.simpleLogger.logFile=output.log
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.showShortLogName=true
org.slf4j.simpleLogger.showThreadName=false
