CREATE TABLE IF NOT EXISTS BINDERS
(
    ID       VARCHAR(128)          NOT NULL PRIMARY KEY,
    SLUG     VARCHAR(128)          NOT NULL,
    ARCHIVED BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS IMAGES
(
    ID              TEXT NOT NULL PRIMARY KEY,
    AVERAGE_HASH    TEXT NOT NULL,
    DIFFERENCE_HASH TEXT NOT NULL,
    MEDIAN_HASH     TEXT NOT NULL,
    PERCEPTIVE_HASH TEXT NOT NULL,
    ROTATIONAL_HASH TEXT NOT NULL
);
