CREATE TABLE IF NOT EXISTS "sets"
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    BINDER      VARCHAR(128) NOT NULL,
    DESCRIPTION TEXT         NULL,
    "date"      DATE         NULL,
    CREATED_AT  DATE         NOT NULL,
    FINISHED_AT DATE         NULL
);

ALTER TABLE "sets"
    ADD CONSTRAINT FK_SETS_BINDER__ID
        FOREIGN KEY (BINDER) REFERENCES BINDERS (ID)
            ON DELETE RESTRICT ON UPDATE RESTRICT;
