ALTER TABLE IMAGES
    ADD COLUMN SET_ID BIGINT NOT NULL DEFAULT 0;

ALTER TABLE IMAGES
    ADD COLUMN INT BIGINT NOT NULL DEFAULT 0;

ALTER TABLE IMAGES
    ADD CONSTRAINT FK_IMAGES_SET_ID__ID
        FOREIGN KEY (SET_ID) REFERENCES "sets" (ID)
            ON DELETE RESTRICT ON UPDATE RESTRICT;
