ALTER TABLE IMAGES
    ADD COLUMN BINDER_ID VARCHAR(128) NOT NULL DEFAULT 0;

ALTER TABLE IMAGES
	ADD CONSTRAINT FK_IMAGES_BINDER__ID
		FOREIGN KEY (BINDER_ID) REFERENCES BINDERS (ID)
			ON DELETE RESTRICT ON UPDATE RESTRICT;
