name: CI (Branch/Merge Group/PR)

on:
  push:
    branches-ignore:
      - root

  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4

        with:
          java-version: 24
          distribution: temurin

      - name: Gradle (Setup)
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle (Build)
        run: "./gradlew checkLicenses build"
